language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - libzmq-dev
before_install:
  - npm install -g typescript
script:
  - npm test
  - npm run lint
  - npm run coverage